### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by harshahota** [StephenGrider/JSPlaygrounds#15]
hello,
I am getting an error message 
TypeError: OPEN_DELIMITERS.includes is not a function in chrome when i try to write something.
please help

**Comment by oluomoniyi** [comment]
Getting same error, with the JS below.

```
var test = "test"
test
```

**Comment by helton** [comment]
It's probably a browser compatibility issue.
Whoever is having this problem, take a look at the MDN `Array.prototype.includes` method, section **Browser compatibility** and make sure you have at least the version listed there for your current browser.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
